### PR TITLE
Dirac tests

### PR DESCRIPTION
**Pull request by djauty**

### CODE REVIEW

**Comment by mjmottram** [comment]
PR looks good.  Is there a way the list of CEs can be scraped (or at least entered by hand) from http://www.hep.ph.ic.ac.uk/~dbauer/dirac/site_pilot_status.html?  Anything with a YES in the snoplus.snolab.ca column is enabled for SNO+.

**Comment by djauty** [comment]
I added the list so people could see what we could upload to. The snoplus.snolab.ca was off my browser when I look at this page before so I copied all sites. I've updated the list so it is now just the ones with yes next to the name and McGill. Maybe I sould have an option so the user can test other sites. Wait till my next commit before accepting the pull request I'll change it

**Comment by djauty** [comment]
Okay in the previous commit canged so only snoplus.snolab.ca active sites were part of the list. Now if you enter a non-list site you can type yes to use that instead or anything else not to submit.

**Comment by mjmottram** [comment]
Forgot about this, sorry!  Merging!

**Pull request merged**
